select
    md5(country_natural_key) as country_key,
    country_natural_key,
    country_id,
    country_code_alpha_2,
    country_code_alpha_3,
    country_name,
    official_name,
    region,
    subregion,
    continent,
    capital_name,
    population,
    area_square_km,
    latitude,
    longitude,
    is_landlocked,
    is_sovereign,
    is_un_member,
    government_type,
    driving_side,
    flag_emoji,
    flag_png_url,
    flag_svg_url,
    primary_top_level_domain,
    primary_calling_code,
    ingestion_id,
    loaded_at

from {{ ref('int_countries') }}